spike = User.create(email: "spike@bebop.com", password_digest: "not implemented yet")
Task.create(description: "Take Ein for a walk", user_id: spike.id)
Task.create(description: "Get a haircut", user_id: spike.id)
Task.create(description: "See if dinner is ready", user_id: spike.id)
Task.create(description: "Watch tonight's Big Shot", user_id: spike.id)
